from __future__ import annotations

from ..schemas import TeacherCohortScorecard


def build_teacher_cohort_scorecard(
    *,
    cohort_key: str,
    fleet_id: str,
    window_id: str,
    threshold_set_id: str,
    threshold_version: int,
    subject: str | None,
    teacher_pair_id: str | None,
    budget_class: str | None,
    hardware_class: str | None,
    lineage: str | None,
    run_count: int,
    valid_run_count: int,
    stability_score: float,
    variance: float,
    disagreement_trend: float,
    outperformance_consistency: float,
    regression_spike_count: int,
    rollback_risk: float,
    dream_contamination_sensitivity: float,
    hardware_sensitivity: float,
    stable: bool,
    ready: bool,
    fleet_summary_ids: list[str],
    takeover_scorecard_ids: list[str],
    metrics: dict,
) -> TeacherCohortScorecard:
    return TeacherCohortScorecard(
        cohort_key=cohort_key,
        fleet_id=fleet_id,
        window_id=window_id,
        threshold_set_id=threshold_set_id,
        threshold_version=threshold_version,
        subject=subject,
        teacher_pair_id=teacher_pair_id,
        budget_class=budget_class,
        hardware_class=hardware_class,
        lineage=lineage,
        run_count=run_count,
        valid_run_count=valid_run_count,
        stability_score=stability_score,
        variance=variance,
        disagreement_trend=disagreement_trend,
        outperformance_consistency=outperformance_consistency,
        regression_spike_count=regression_spike_count,
        rollback_risk=rollback_risk,
        dream_contamination_sensitivity=dream_contamination_sensitivity,
        hardware_sensitivity=hardware_sensitivity,
        stable=stable,
        ready=ready,
        fleet_summary_ids=fleet_summary_ids,
        takeover_scorecard_ids=takeover_scorecard_ids,
        metrics=metrics,
    )
