services:
  nexusnet:
    build: ./docker
    ports: ["5173:5173"]
    volumes:
      - ./runtime:/app/runtime
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
      - REQUESTY_API_KEY=${REQUESTY_API_KEY:-}