thresholds:
  min_interactions_per_expert: 50
  min_ais_coverage: 0.80
  min_citation_rate: 0.80
  notify_creator_when_ready: true
  leaderboard_gate: true
leaderboards:
  - name: "Open LLM Leaderboard"
    url: "https://example.com/llm-leaderboard"
  - name: "Chatbot Arena"
    url: "https://example.com/chatbot-arena"
notify:
  webhook: ""
  email: ""
