
capsules:
  coder: {enabled: true, teachers: ["codellama/CodeLlama-7b-Python-hf"]}
  strategist: {enabled: true, teachers: ["mistralai/Mixtral-8x7B-Instruct-v0.1"]}
  analyst: {enabled: true, teachers: ["Qwen/Qwen2-7B-Instruct"]}
  researcher: {enabled: true, teachers: ["allenai/OLMo-7B-Instruct"]}
  critique: {enabled: true, teachers: ["openchat/openchat-3.5"]}
  conversationalist: {enabled: true, teachers: ["TinyLlama/TinyLlama-1.1B-Chat-v1.0"]}
  toolsmith: {enabled: true, teachers: ["mlx-community/Mistral-7B-Instruct-v0.2"]}
  security: {enabled: true, teachers: ["Meta-Llama-3-8B-Instruct"]}
  memory_weaver: {enabled: true, teachers: ["bge-small-en"]}
  meta_reasoner: {enabled: true, teachers: ["DeepSeek-R1-Distill-Qwen-7B"]}
  router: {enabled: true, teachers: ["Yi-1.5-9B-Chat"]}
  linguist: {enabled: true, teachers: ["Nous-Hermes-2-Mixtral-8x7B"]}
  vision: {enabled: true, teachers: ["llava-hf/llava-1.5-7b-hf"]}
  audio: {enabled: true, teachers: ["whisper-small"]}
  simulation: {enabled: true, teachers: ["Phi-3-mini-128k-instruct"]}
  builder: {enabled: true, teachers: ["OpenHermes-2.5-Mistral-7B"]}
  instructor: {enabled: true, teachers: ["Mistral-7B-Instruct-v0.3"]}
  intent_mapper: {enabled: true, teachers: ["google/gemma-2b-it"]}
  critic_historian: {enabled: true, teachers: ["Tulu-2-DPO-70B"]}
