hivemind:
  consensus_method: "weighted_vote"  # weighted_vote, majority, confidence_based
  min_experts: 3
  max_experts: 19
  voting_weights:
    confidence: 0.4
    diversity: 0.3
    accuracy: 0.3
  
  # Expert selection strategy
  selection_strategy: "dynamic"  # static, dynamic, adaptive
  
  # Confidence thresholds
  min_confidence: 0.6
  consensus_threshold: 0.75
  
  # Fallback behavior
  fallback_to_generalist: true
  fallback_confidence: 0.5

execution:
  parallel_processing: true
  max_concurrent_experts: 5
  timeout_seconds: 30
  
  # Response aggregation
  aggregation_method: "ranked_fusion"  # simple_vote, ranked_fusion, weighted_average
  
  # Quality control
  enable_cross_validation: true
  cross_validation_threshold: 0.8
