nodes:
  - generalist
  - search
  - research
  - code
  - math
  - data_science
  - devops
  - cybersecurity
  - legal
  - medical
  - finance
  - translation
  - writing
  - education
  - design
  - marketing
  - product
  - operations
  - vision
edges:
  generalist: [search, research, writing]
  search: [research, generalist]
  research: [writing, generalist, education]
  code: [devops, data_science]
  math: [data_science]
  data_science: [math, code]
  devops: [operations, product]
  cybersecurity: [devops, operations]
  legal: [finance, operations]
  medical: [research, education]
  finance: [product, operations]
  translation: [writing, education]
  writing: [design, marketing]
  education: [writing, generalist]
  design: [product, marketing]
  marketing: [product, operations]
  product: [operations, code]
  operations: [product, devops]
  vision: [research, design]
arbitration:
  max_steps: 3
  vote: 'consensus'
  coverage_floor: 0.75
  use_llm_judge: true
