rag:
  query_transform: { enable: true, enable_hyde: true, n_rewrites: 4, max_chars: 220, budget_max_embeddings: 64 }
  retrieval:
    stage1: { vector_k: 30, bm25_k: 30, use_bm25_hybrid: true, rrf_k: 60 }
    stage2: { reranker: cross_encoder, cross_encoder_model: cross-encoder/ms-marco-MiniLM-L6-v2, topk: 8 }
  
  agentic:
    enabled: true
    max_steps: 5
    coverage_threshold: 0.80
    planner_model: "gpt-4"

models:
  planner_verifier: { prefer_provider: false, tiny_name: TinyLlama/TinyLlama-1.1B-Chat-v1.0 }
  embedder: BAAI/bge-small-en-v1.5
  ais_nli: microsoft/deberta-v3-base-mnli
  reranker: cross-encoder/ms-marco-MiniLM-L6-v2

late_interaction:
  enable: true
  backend: colbert
  index_dir: runtime/state/colbert_index
  model: colbert-ir/colbertv2.0
  doc_maxlen: 180
  nbits: 2
  kmeans_niters: 4
  nprobe: 64
  topk: 50

temporal:
  enabled: true
  recency_lambda: 0.15
  default_lookback_days: 365
  enforce_answer_dates: true

fl:
  enabled: false
  coordinator_url: http://127.0.0.1:8088
  eps_budget: 1.0
  sigma: 0.7
  clip: 0.2

rag.graph.stop: { coverage_threshold: 0.80, max_steps: 5 }