
engine_order:
  - transformers
  - ollama
  - lmstudio
  - vllm_http
  - llamacpp
defaults:
  model_id: ${NEXUSNET_MODEL_ID:-TinyLlama/TinyLlama-1.1B-Chat-v1.0}
  max_new_tokens: 256
  temperature: 0.7
  top_p: 0.95
safety:
  max_input_chars: 8000
  pii_redact: true

features:
  experts: true
  dreamer: false
  teacher_gate_force: false
  cors_any_origin: true
