global:
  max_len: 4096
  diversity_target: 0.3
experts:
  code: { style: "step-by-step with runnable snippets", rejection_rate_max: 0.1 }
  math: { style: "chain-of-thought to tool calls (hidden)", rejection_rate_max: 0.15 }
  legal: { style: "cite statute/case [#] and disclaim", rejection_rate_max: 0.1 }
  medical: { style: "evidence-based, safety-first, cite [#]", rejection_rate_max: 0.1 }
  research: { style: "quote+cite [#], AIS>=0.9", rejection_rate_max: 0.05 }
