
name: licenses
on:
  push:
    branches: [ main ]
jobs:
  pip-licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.11"}
      - run: |
          python -m pip install -U pip pip-licenses
          pip-licenses --format=markdown > THIRD_PARTY_LICENSES.md || true
      - uses: actions/upload-artifact@v4
        with:
          name: third-party-licenses
          path: THIRD_PARTY_LICENSES.md
