
name: sbom
on:
  push:
    branches: [ main ]
jobs:
  cyclonedx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.11"}
      - run: |
          python -m pip install -U pip cyclonedx-bom
          cyclonedx-py -e -o sbom.json || true
      - uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
